// AUTO-GENERATED by tools/generate-tokens.mjs from tokens.json.
// Do not edit by hand.
import SwiftUI

/// Design tokens shared with the web (`_tokens.scss` / `tokens.ts`).
/// Durations are SECONDS (web twins carry milliseconds).
public enum AlloyTokens {
    public static let tint = Color(red: 10 / 255.0, green: 132 / 255.0, blue: 255 / 255.0, opacity: 1)
    public static let tintHover = Color(red: 38 / 255.0, green: 145 / 255.0, blue: 255 / 255.0, opacity: 1)
    public static let live = Color(red: 48 / 255.0, green: 209 / 255.0, blue: 88 / 255.0, opacity: 1)
    public static let mock = Color(red: 255 / 255.0, green: 159 / 255.0, blue: 10 / 255.0, opacity: 1)
    public static let destructive = Color(red: 255 / 255.0, green: 69 / 255.0, blue: 58 / 255.0, opacity: 1)
    public static let sheetBg = Color(red: 28 / 255.0, green: 28 / 255.0, blue: 30 / 255.0, opacity: 1)
    public static let secondarySurface = Color(red: 118 / 255.0, green: 118 / 255.0, blue: 128 / 255.0, opacity: 0.24)
    public static let secondarySurfaceHover = Color(red: 118 / 255.0, green: 118 / 255.0, blue: 128 / 255.0, opacity: 0.34)
    public static let grabHandle = Color(red: 85 / 255.0, green: 85 / 255.0, blue: 85 / 255.0, opacity: 1)
    public static let label = Color(red: 255 / 255.0, green: 255 / 255.0, blue: 255 / 255.0, opacity: 1)
    public static let secondaryLabel = Color(red: 152 / 255.0, green: 152 / 255.0, blue: 158 / 255.0, opacity: 1)
    public static let track = Color(red: 255 / 255.0, green: 255 / 255.0, blue: 255 / 255.0, opacity: 0.16)
    public static let backdrop = Color(red: 0 / 255.0, green: 0 / 255.0, blue: 0 / 255.0, opacity: 0.4)
    public static let knobCard = Color(red: 255 / 255.0, green: 255 / 255.0, blue: 255 / 255.0, opacity: 0.04)

    public static let sheetAnimation: Double = 0.28
    public static let autoHide: Double = 2.5
    public static let chromeFade: Double = 0.3
    public static let snackbarShow: Double = 4
    public static let overlayFade: Double = 0.15

    public static let sheetCornerRadius: CGFloat = 24
}
