#!/usr/bin/env node
// Emit _tokens.scss (web), tokens.ts (web), AlloyTokens.swift (iOS) from
// tokens.json — the single source of truth. Never edit the outputs by hand.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(join(root, 'tokens.json'), 'utf8'));

const header = (syntax) => `${syntax} AUTO-GENERATED by tools/generate-tokens.mjs from tokens.json.
${syntax} Do not edit by hand.\n`;

// ---- SCSS ----
const scssColors = Object.entries(tokens.color)
  .map(([k, v]) => `$${k}: ${v};`)
  .join('\n');
writeFileSync(
  join(root, 'web/packages/alloy-ui/src/styles/_tokens.scss'),
  header('//') + scssColors + '\n'
);

// ---- TS (durations; SCREAMING_SNAKE with _MS suffix) ----
const tsDurations = Object.entries(tokens.durationMs)
  .map(([k, v]) => `export const ${k.toUpperCase().replace(/-/g, '_')}_MS = ${v};`)
  .join('\n');
writeFileSync(
  join(root, 'web/packages/alloy-ui/src/lib/tokens.ts'),
  header('//') + tsDurations + '\n'
);

// ---- Swift ----
function swiftColor(value) {
  const hex = /^#([0-9a-f]{6})$/i.exec(value);
  if (hex) {
    const n = parseInt(hex[1], 16);
    return colorLiteral((n >> 16) & 255, (n >> 8) & 255, n & 255, 1);
  }
  const rgba = /^rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)$/.exec(value);
  if (rgba) return colorLiteral(+rgba[1], +rgba[2], +rgba[3], +rgba[4]);
  throw new Error(`unsupported color format: ${value}`);
}
const colorLiteral = (r, g, b, a) =>
  `Color(red: ${r} / 255.0, green: ${g} / 255.0, blue: ${b} / 255.0, opacity: ${a})`;
const camel = (k) => k.replace(/-(\w)/g, (_, c) => c.toUpperCase());

const swiftColors = Object.entries(tokens.color)
  .map(([k, v]) => `    public static let ${camel(k)} = ${swiftColor(v)}`)
  .join('\n');
const swiftDurations = Object.entries(tokens.durationMs)
  .map(([k, v]) => `    public static let ${camel(k)}: Double = ${v / 1000}`)
  .join('\n');
writeFileSync(
  join(root, 'swift/Sources/AlloyUI/AlloyTokens.swift'),
  header('//') +
    `import SwiftUI

/// Design tokens shared with the web (\`_tokens.scss\` / \`tokens.ts\`).
/// Durations are SECONDS (web twins carry milliseconds).
public enum AlloyTokens {
${swiftColors}

${swiftDurations}
}
`
);
console.log('tokens generated (scss, ts, swift)');
