// AUTO-GENERATED by tools/generate-tokens.mjs from tokens.json.
// Do not edit by hand.
export const SHEET_ANIMATION_MS = 280;
export const AUTO_HIDE_MS = 2500;
export const SHEET_CORNER_RADIUS_PX = 24;
